name: Scheduled Nightly Build
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '* */2 * * *'
jobs:
  schedule-task:
    runs-on: ubuntu-latest
    steps:
      - name: Create a tag for the archive
        id: tag
        # The `set-output` command is deprecated and will be disabled soon. using environment files instead  https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#environment-files
        # run: echo "::set-output name=TAG::$(date +%F)" 
        run: echo "TAG=$(date +%F)" >> $GITHUB_ENV
        
        
      - name: Starting the nightly build for $TAG old
        env:
          TAG: ${{ steps.tag.outputs.TAG }}
        # run: echo "The tag is ${{ steps.tag.outputs.TAG }}"
        run: echo "The tag is $TAG"
        
      - name: Starting the nightly build for $TAG 
        run: echo "The tag is $TAG"

      - name: Check out the code
        uses: actions/checkout@v4
        
      - name: Create the artifact old
        run: tar -cvf nightly-${{ steps.tag.outputs.TAG }}.tar ./*
        # run: tar -cvf nightly-$TAG.tar ./*

      - name: Create the artifact
        # run: tar -cvf nightly-${{ steps.tag.outputs.TAG }}.tar ./*
        run: tar -cvf nightly-$TAG.tar ./*
        
      # - name: Upload the artifact
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: nightly-${TAG}.tar
      #     path: nightly-${TAG}.tar
          # name: nightly-${{ steps.tag.outputs.TAG }}.tar
          # path: nightly-${{ steps.tag.outputs.TAG }}.tar

