name: Scheduled Nightly Build
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'
jobs:
  date:
    runs-on: ubuntu-latest
    steps:
      - name: Create a tag for the archive
        # The `set-output` command is deprecated and will be disabled soon. 
        # run: echo "::set-output name=TAG::$(date +%F)" 
        run: echo "{name}={value}" >> $GITHUB_OUTPUT
        id: tag
        
      - name: Starting the nightly build for ${{ steps.tag.outputs.TAG }}
        run: echo "The tag is ${{ steps.tag.outputs.TAG }}"
        
      - name: Check out the code
        uses: actions/checkout@v4
        
      - name: Create the artifact
        run: tar -cvf nightly-${{ steps.tag.outputs.TAG }}.tar ./*
        
      - name: Upload the artifact
        uses: actions/upload-artifact@v3
        with:
         name: nightly-${{ steps.tag.outputs.TAG }}.tar
         path: nightly-${{ steps.tag.outputs.TAG }}.tar

