name: Service Container Seed Database
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  #可以手动触发
  workflow_dispatch:

env:
  DATABASE_USER: test_user
  DATABASE_PASS: test_password
  DATABASE_NAME: testdb
  DATABASE_PORT: 5432

jobs:
  build:
    runs-on: ubuntu-latest
    # 这一步自动识别为Initialize containers
    services:
      postgres:
        image: postgres:16.1
        env:
          POSTGRES_USER: ${{ env.DATABASE_USER }}
          POSTGRES_PASSWORD: ${{ env.DATABASE_PASS }}
          POSTGRES_DB: ${{ env.DATABASE_NAME }}
        volumes:
          - /source/directory:/destination/directory
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Seed the database
        run: python seed_database.py
        env:
          DATABASE_HOST: localhost
          DATABASE_NAME: ${{ env.DATABASE_NAME }}
          DATABASE_USER: ${{ env.DATABASE_USER }}
          DATABASE_PASS: ${{ env.DATABASE_PASS }}
          DATABASE_PORT: ${{ env.DATABASE_PORT }}
